// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQyVQt8xbdGOAnELM6LuLP5wvNDPQY_DI',
    appId: '1:1054949292448:android:d0f12331a01963426e4cc5',
    messagingSenderId: '1054949292448',
    projectId: 'fdsmart-fdace',
    storageBucket: 'fdsmart-fdace.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATzSl2Plni37R1BI1atgupqaQ1Qy_M0vw',
    appId: '1:1054949292448:web:2fee8f6a1f0a2d576e4cc5',
    messagingSenderId: '1054949292448',
    projectId: 'fdsmart-fdace',
    authDomain: 'fdsmart-fdace.firebaseapp.com',
    storageBucket: 'fdsmart-fdace.firebasestorage.app',
    measurementId: 'G-35C8HER3T1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnoEV-EFlBpeEYBpnBIClC89oT3g3NgxE',
    appId: '1:1054949292448:ios:4d104b3400f01de86e4cc5',
    messagingSenderId: '1054949292448',
    projectId: 'fdsmart-fdace',
    storageBucket: 'fdsmart-fdace.firebasestorage.app',
    iosClientId: '1054949292448-gacha5hf7kamkogi63df659gldhdkla0.apps.googleusercontent.com',
    iosBundleId: 'com.fdsmart.fdsmart',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnoEV-EFlBpeEYBpnBIClC89oT3g3NgxE',
    appId: '1:1054949292448:ios:4d104b3400f01de86e4cc5',
    messagingSenderId: '1054949292448',
    projectId: 'fdsmart-fdace',
    storageBucket: 'fdsmart-fdace.firebasestorage.app',
    iosClientId: '1054949292448-gacha5hf7kamkogi63df659gldhdkla0.apps.googleusercontent.com',
    iosBundleId: 'com.fdsmart.fdsmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATzSl2Plni37R1BI1atgupqaQ1Qy_M0vw',
    appId: '1:1054949292448:web:2bdffd90d048ba856e4cc5',
    messagingSenderId: '1054949292448',
    projectId: 'fdsmart-fdace',
    authDomain: 'fdsmart-fdace.firebaseapp.com',
    storageBucket: 'fdsmart-fdace.firebasestorage.app',
    measurementId: 'G-NWVPGF5HZJ',
  );

}